http:
  userAgent: "polymind/0.1"
  timeout: "10s"
  poolIdleTimeout: "30s"
  poolMaxIdlePerHost: 16
  tcpKeepAlive: "30s"

polymarket:
  baseUrl: "https://api.polymarket.com"
  gammaEventsUrl: "https://gamma-api.polymarket.com/events"
  gammaMarketsUrl: "https://gamma-api.polymarket.com/markets"
  rpcUrl: "https://polygon-rpc.com"
  dataApiUrl: "https://data-api.polymarket.com"
  marketListRefresh: "300s"
  pageLimit: 100

rss:
  refresh: "10s"
  concurrency: 16
  feeds:
#    - id: "bbc"
#      url: "http://feeds.bbci.co.uk/news/world/rss.xml"
    - id: "cnn"
      url: "http://rss.cnn.com/rss/edition_world.rss"
    - id: "cnbc"
      url: "https://www.cnbc.com/id/100727362/device/rss/rss.html"
#    - id: "ndtv"
#      url: "http://feeds.feedburner.com/ndtvnews-world-news"
    - id: "nyt"
      url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml"
#    - id: "wpost"
#      url: "http://feeds.washingtonpost.com/rss/world"
    - id: "google"
      url: "https://news.google.com/rss"
#    - id: "reddit"
#      url: "https://www.reddit.com/r/worldnews/.rss"
    - id: "yahoo-fin"
      url: "https://news.yahoo.com/rss/finance"
    - id: "guardian"
      url: "https://www.theguardian.com/world/rss"

financialJuice:
  baseUrl: "https://www.financialjuice.com/"
  altUrl: "https://live.financialjuice.com/FJService.asmx/Startup"
  info: "%22EAAAADyxhXfpGMQesDtGBUqmT8eYX0feSuQ3O7zMSuHnGXYhgVERjD1oCDt1gCc7VA%2B2A3rh2MNmMLOm3H9erZ%2Fncqf1JKZe6J%2BgB9CACwSLODRlnVZjKuBJB%2FHfF7%2BpXRPGjZcwgloeGsLbUb%2BA6tnMd7gYKDoXbUY7YcF9GJUrpzJHpSbXgxA90MVcitNMEjXjALB6tasgaT53eSIYy%2FC%2FJAtadH1Fk7fneZCwfcz6mSMGfEzWlAIPlJANxkfKayBJ6SMH%2BHFh5HflgrpWgQvQGb2mwPgaCiaXwTJ%2Ba5SBv0HnfhEJixMY9GD9%2BlYX9FUodIiaVmrSZzKKdL%2BDhjpCOc0%3D%22"
  refresh: "10s"

strategy:
  simExecution: true
  simMarketData: true
  topCandidates: 5
  maxPositionDrawdownPct: 0.2

llm:
  model: "gpt-5-nano"
  baseUrl: "https://api.openai.com/v1"